### ISSUE TITLE
引擎是cx_Oracle时能否采用pydbclib.connect().read().get_all()语法查询？

### ISSUE THREAD

**Issue by laferce** [taogeYT/pydbclib#5]
我希望用统一的代码操作 MySQL、SQL Server、Oracle，当引擎是 pymssql 或 pymysql 时，都能用以下语法执行：

con = pydbclib.connect(driver = 'xxxx', host, port, user, password)
record = con.read(sql, as_dict = Fasle).get_all()

获得 sql 的查询结果；但引擎是 cx_Oracle 时，同样的操作：

con = pydbclib.connect(driver = 'cx_Oracle', user = 'sys', password = 'xx', dsn = 'xxxx', mode = cx_Oracle.SYSDBA)
record = con.read(sql, as_dict = False).get_all()

会报错：

Traceback (most recent call last):
  File "d:/test/test.py", line 999, in GetTables
    try:r = c.read('select table_name from tabs', as_dict=False).get_all()
  File "D:\test\lib\site-packages\pydbclib\database.py", line 126, in read
    self.driver.execute(sql, args)
  File "D:\test\lib\site-packages\pydbclib\drivers.py", line 107, in execute
    sql, params = self.compiler(sql, params).process_one()
AttributeError: 'Compiler' object has no attribute 'process_one'

该如何正确使用 pydbclib 来确保统一体验？

**Comment by taogeYT** [comment]
2.2.3版本修复
